<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>AutoTrader</RootNamespace>
    <AssemblyName>AutoTrader</AssemblyName>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>bin/Win64_Shipping_Client/</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="src/**/*.cs"
             Exclude="src/AutoTradeMenuGauntletScreen.cs;src/AutoTraderMenuViewModel.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="GUI/Prefabs/**/*" />
    <None Include="ModuleData/**/*" />
    <None Include="SubModule.xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MountAndBlade.ReferenceAssemblies" Version="1.0.0" />
  </ItemGroup>
  <Target Name="CopyModuleAssets" AfterTargets="Build">
    <ItemGroup>
      <ModuleAssets Include="ModuleData\**\*;GUI\Prefabs\**\*;SubModule.xml" />
    </ItemGroup>
    <Copy SourceFiles="@(ModuleAssets)" DestinationFiles="@(ModuleAssets->'$(MSBuildProjectDirectory)\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
  </Target>
</Project>
